// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passengerfeedback.proto

package passengerfeedback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCode) Reset()         { *m = ResponseCode{} }
func (m *ResponseCode) String() string { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()    {}
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{0}
}

func (m *ResponseCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCode.Unmarshal(m, b)
}
func (m *ResponseCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCode.Marshal(b, m, deterministic)
}
func (m *ResponseCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCode.Merge(m, src)
}
func (m *ResponseCode) XXX_Size() int {
	return xxx_messageInfo_ResponseCode.Size(m)
}
func (m *ResponseCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCode proto.InternalMessageInfo

func (m *ResponseCode) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCode) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PassengerFeedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedback) Reset()         { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()    {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{1}
}

func (m *PassengerFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedback.Unmarshal(m, b)
}
func (m *PassengerFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedback.Marshal(b, m, deterministic)
}
func (m *PassengerFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedback.Merge(m, src)
}
func (m *PassengerFeedback) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedback.Size(m)
}
func (m *PassengerFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedback proto.InternalMessageInfo

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type AddPassengerFeedbackResult struct {
	ResponseCode         *ResponseCode `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddPassengerFeedbackResult) Reset()         { *m = AddPassengerFeedbackResult{} }
func (m *AddPassengerFeedbackResult) String() string { return proto.CompactTextString(m) }
func (*AddPassengerFeedbackResult) ProtoMessage()    {}
func (*AddPassengerFeedbackResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{2}
}

func (m *AddPassengerFeedbackResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPassengerFeedbackResult.Unmarshal(m, b)
}
func (m *AddPassengerFeedbackResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPassengerFeedbackResult.Marshal(b, m, deterministic)
}
func (m *AddPassengerFeedbackResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPassengerFeedbackResult.Merge(m, src)
}
func (m *AddPassengerFeedbackResult) XXX_Size() int {
	return xxx_messageInfo_AddPassengerFeedbackResult.Size(m)
}
func (m *AddPassengerFeedbackResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPassengerFeedbackResult.DiscardUnknown(m)
}

var xxx_messageInfo_AddPassengerFeedbackResult proto.InternalMessageInfo

func (m *AddPassengerFeedbackResult) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

type GetPassengerFeedbackRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPassengerFeedbackRequest) Reset()         { *m = GetPassengerFeedbackRequest{} }
func (m *GetPassengerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbackRequest) ProtoMessage()    {}
func (*GetPassengerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{3}
}

func (m *GetPassengerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbackRequest.Unmarshal(m, b)
}
func (m *GetPassengerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbackRequest.Merge(m, src)
}
func (m *GetPassengerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbackRequest.Size(m)
}
func (m *GetPassengerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbackRequest proto.InternalMessageInfo

func (m *GetPassengerFeedbackRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *GetPassengerFeedbackRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type GetPassengerFeedbackCodeResponse struct {
	ResponseCode         *ResponseCode      `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	PassengerFeedback    *PassengerFeedback `protobuf:"bytes,2,opt,name=passengerFeedback,proto3" json:"passengerFeedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPassengerFeedbackCodeResponse) Reset()         { *m = GetPassengerFeedbackCodeResponse{} }
func (m *GetPassengerFeedbackCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbackCodeResponse) ProtoMessage()    {}
func (*GetPassengerFeedbackCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{4}
}

func (m *GetPassengerFeedbackCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbackCodeResponse.Unmarshal(m, b)
}
func (m *GetPassengerFeedbackCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbackCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbackCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbackCodeResponse.Merge(m, src)
}
func (m *GetPassengerFeedbackCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbackCodeResponse.Size(m)
}
func (m *GetPassengerFeedbackCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbackCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbackCodeResponse proto.InternalMessageInfo

func (m *GetPassengerFeedbackCodeResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func (m *GetPassengerFeedbackCodeResponse) GetPassengerFeedback() *PassengerFeedback {
	if m != nil {
		return m.PassengerFeedback
	}
	return nil
}

type GetPassengerFeedbackIDResponse struct {
	ResponseCode         *ResponseCode        `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	PassengerFeedbacks   []*PassengerFeedback `protobuf:"bytes,2,rep,name=passengerFeedbacks,proto3" json:"passengerFeedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPassengerFeedbackIDResponse) Reset()         { *m = GetPassengerFeedbackIDResponse{} }
func (m *GetPassengerFeedbackIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPassengerFeedbackIDResponse) ProtoMessage()    {}
func (*GetPassengerFeedbackIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{5}
}

func (m *GetPassengerFeedbackIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerFeedbackIDResponse.Unmarshal(m, b)
}
func (m *GetPassengerFeedbackIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerFeedbackIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPassengerFeedbackIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerFeedbackIDResponse.Merge(m, src)
}
func (m *GetPassengerFeedbackIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPassengerFeedbackIDResponse.Size(m)
}
func (m *GetPassengerFeedbackIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerFeedbackIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerFeedbackIDResponse proto.InternalMessageInfo

func (m *GetPassengerFeedbackIDResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func (m *GetPassengerFeedbackIDResponse) GetPassengerFeedbacks() []*PassengerFeedback {
	if m != nil {
		return m.PassengerFeedbacks
	}
	return nil
}

type DeletePassengerFeedbackRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePassengerFeedbackRequest) Reset()         { *m = DeletePassengerFeedbackRequest{} }
func (m *DeletePassengerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePassengerFeedbackRequest) ProtoMessage()    {}
func (*DeletePassengerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{6}
}

func (m *DeletePassengerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePassengerFeedbackRequest.Unmarshal(m, b)
}
func (m *DeletePassengerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePassengerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *DeletePassengerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePassengerFeedbackRequest.Merge(m, src)
}
func (m *DeletePassengerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePassengerFeedbackRequest.Size(m)
}
func (m *DeletePassengerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePassengerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePassengerFeedbackRequest proto.InternalMessageInfo

func (m *DeletePassengerFeedbackRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type DeletePassengerFeedbackResponse struct {
	ResponseCode         *ResponseCode `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeletePassengerFeedbackResponse) Reset()         { *m = DeletePassengerFeedbackResponse{} }
func (m *DeletePassengerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePassengerFeedbackResponse) ProtoMessage()    {}
func (*DeletePassengerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbe323b0704a1f6c, []int{7}
}

func (m *DeletePassengerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePassengerFeedbackResponse.Unmarshal(m, b)
}
func (m *DeletePassengerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePassengerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *DeletePassengerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePassengerFeedbackResponse.Merge(m, src)
}
func (m *DeletePassengerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePassengerFeedbackResponse.Size(m)
}
func (m *DeletePassengerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePassengerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePassengerFeedbackResponse proto.InternalMessageInfo

func (m *DeletePassengerFeedbackResponse) GetResponseCode() *ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseCode)(nil), "passengerfeedback.ResponseCode")
	proto.RegisterType((*PassengerFeedback)(nil), "passengerfeedback.PassengerFeedback")
	proto.RegisterType((*AddPassengerFeedbackResult)(nil), "passengerfeedback.AddPassengerFeedbackResult")
	proto.RegisterType((*GetPassengerFeedbackRequest)(nil), "passengerfeedback.GetPassengerFeedbackRequest")
	proto.RegisterType((*GetPassengerFeedbackCodeResponse)(nil), "passengerfeedback.GetPassengerFeedbackCodeResponse")
	proto.RegisterType((*GetPassengerFeedbackIDResponse)(nil), "passengerfeedback.GetPassengerFeedbackIDResponse")
	proto.RegisterType((*DeletePassengerFeedbackRequest)(nil), "passengerfeedback.DeletePassengerFeedbackRequest")
	proto.RegisterType((*DeletePassengerFeedbackResponse)(nil), "passengerfeedback.DeletePassengerFeedbackResponse")
}

func init() { proto.RegisterFile("passengerfeedback.proto", fileDescriptor_fbe323b0704a1f6c) }

var fileDescriptor_fbe323b0704a1f6c = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0x29, 0x7f, 0x7e, 0x3f, 0x19, 0xb8, 0x30, 0x31, 0xb1, 0xa9, 0x09, 0xd4, 0x8d, 0x07,
	0x2e, 0x92, 0x58, 0xae, 0x5e, 0x04, 0xa2, 0xe1, 0x66, 0x56, 0x5f, 0xa0, 0xd0, 0x81, 0x10, 0xfe,
	0x14, 0xbb, 0xc5, 0xc4, 0x37, 0x30, 0x26, 0x3e, 0x8c, 0x67, 0x5f, 0xce, 0xb0, 0xa1, 0xb0, 0x66,
	0xb7, 0xa4, 0x24, 0xbd, 0xb1, 0xcb, 0xcc, 0xf7, 0xfb, 0x99, 0x99, 0x9d, 0xc2, 0xc5, 0xda, 0x17,
	0x82, 0x56, 0x53, 0x8a, 0x26, 0x44, 0xc1, 0xc8, 0x1f, 0xcf, 0x3b, 0xeb, 0x28, 0x8c, 0x43, 0x6c,
	0x68, 0x7f, 0xb0, 0x3b, 0xa8, 0x73, 0x12, 0xeb, 0x70, 0x25, 0xa8, 0x1f, 0x06, 0x84, 0x08, 0xe5,
	0x71, 0x18, 0x90, 0x6d, 0xb9, 0x56, 0xbb, 0xc2, 0xe5, 0x6f, 0xb4, 0xe1, 0xff, 0x92, 0x84, 0xf0,
	0xa7, 0x64, 0x17, 0x5d, 0xab, 0x5d, 0xe5, 0xc9, 0x91, 0x09, 0x68, 0x3c, 0x25, 0x92, 0x0f, 0x3b,
	0x49, 0x74, 0xa1, 0x36, 0x0a, 0xc3, 0xf9, 0x6c, 0x35, 0xed, 0x27, 0x4a, 0x55, 0xae, 0x5e, 0x6d,
	0x23, 0xf6, 0x24, 0xc3, 0x81, 0x14, 0xad, 0x70, 0xf5, 0x0a, 0x1d, 0x38, 0x4b, 0x10, 0xed, 0x92,
	0x14, 0xd8, 0x9f, 0x99, 0x0f, 0xce, 0x7d, 0x10, 0x68, 0xbe, 0x9c, 0xc4, 0x66, 0x11, 0x63, 0x1f,
	0xea, 0x91, 0x52, 0x90, 0xb4, 0xaf, 0x79, 0xad, 0x8e, 0xde, 0x13, 0xb5, 0x6e, 0xfe, 0x27, 0x89,
	0xf9, 0x70, 0xf9, 0x48, 0xb1, 0xc1, 0xe2, 0x75, 0x43, 0x22, 0xce, 0xa3, 0x42, 0xf6, 0x63, 0x81,
	0x6b, 0xf2, 0x90, 0x34, 0x3b, 0x96, 0x5c, 0x8a, 0x41, 0x0e, 0x87, 0xb9, 0x27, 0x2e, 0x92, 0xa8,
	0xe6, 0x5d, 0x1b, 0x94, 0xf4, 0xaa, 0xf5, 0xf4, 0x2d, 0x7d, 0xd3, 0x44, 0x3f, 0x1c, 0xe4, 0xcb,
	0xfe, 0x02, 0xa8, 0x99, 0x0b, 0xbb, 0xe8, 0x96, 0x32, 0xc3, 0x1b, 0xf2, 0x59, 0x0f, 0x9a, 0x03,
	0x5a, 0x50, 0x4c, 0xc7, 0x26, 0xac, 0xce, 0xcf, 0xd2, 0xe7, 0x37, 0x81, 0x56, 0xaa, 0x46, 0x8e,
	0x1d, 0xf0, 0xbe, 0xcb, 0x60, 0x6b, 0x16, 0xcf, 0x14, 0xbd, 0xcd, 0xc6, 0x84, 0x4b, 0x38, 0x37,
	0xad, 0x02, 0x66, 0x6a, 0x8d, 0x73, 0x63, 0x88, 0x4a, 0xdf, 0x2c, 0x56, 0xc0, 0x0f, 0x0b, 0xae,
	0x4c, 0x53, 0xef, 0xbd, 0xef, 0xaf, 0x86, 0x01, 0x76, 0x0c, 0xb2, 0x47, 0xb6, 0xc9, 0xb9, 0xcd,
	0x18, 0x7f, 0x78, 0x5b, 0xac, 0x80, 0x9f, 0xa9, 0x28, 0x3d, 0x65, 0x0d, 0x4f, 0x45, 0xe9, 0x66,
	0x8c, 0x57, 0x97, 0x94, 0x15, 0xf0, 0xcb, 0x02, 0x96, 0xf2, 0x18, 0xd4, 0xc6, 0x98, 0x0a, 0x3d,
	0xfe, 0x0e, 0x1d, 0xef, 0x94, 0x94, 0x84, 0x67, 0xf4, 0x4f, 0x7e, 0xee, 0xbb, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x95, 0x85, 0x1c, 0x85, 0x09, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PassengerFeedbackServiceClient is the client API for PassengerFeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerFeedbackServiceClient interface {
	AddPassengerFeedback(ctx context.Context, in *PassengerFeedback, opts ...grpc.CallOption) (*AddPassengerFeedbackResult, error)
	GetPassengerFeedbackByPassengerId(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbackIDResponse, error)
	GetPassengerFeedbackByBookingCode(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbackCodeResponse, error)
	DeletePassengerFeedbackPassengerId(ctx context.Context, in *DeletePassengerFeedbackRequest, opts ...grpc.CallOption) (*DeletePassengerFeedbackResponse, error)
}

type passengerFeedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewPassengerFeedbackServiceClient(cc *grpc.ClientConn) PassengerFeedbackServiceClient {
	return &passengerFeedbackServiceClient{cc}
}

func (c *passengerFeedbackServiceClient) AddPassengerFeedback(ctx context.Context, in *PassengerFeedback, opts ...grpc.CallOption) (*AddPassengerFeedbackResult, error) {
	out := new(AddPassengerFeedbackResult)
	err := c.cc.Invoke(ctx, "/passengerfeedback.PassengerFeedbackService/AddPassengerFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetPassengerFeedbackByPassengerId(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbackIDResponse, error) {
	out := new(GetPassengerFeedbackIDResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.PassengerFeedbackService/GetPassengerFeedbackByPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) GetPassengerFeedbackByBookingCode(ctx context.Context, in *GetPassengerFeedbackRequest, opts ...grpc.CallOption) (*GetPassengerFeedbackCodeResponse, error) {
	out := new(GetPassengerFeedbackCodeResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.PassengerFeedbackService/GetPassengerFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackServiceClient) DeletePassengerFeedbackPassengerId(ctx context.Context, in *DeletePassengerFeedbackRequest, opts ...grpc.CallOption) (*DeletePassengerFeedbackResponse, error) {
	out := new(DeletePassengerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/passengerfeedback.PassengerFeedbackService/DeletePassengerFeedbackPassengerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerFeedbackServiceServer is the server API for PassengerFeedbackService service.
type PassengerFeedbackServiceServer interface {
	AddPassengerFeedback(context.Context, *PassengerFeedback) (*AddPassengerFeedbackResult, error)
	GetPassengerFeedbackByPassengerId(context.Context, *GetPassengerFeedbackRequest) (*GetPassengerFeedbackIDResponse, error)
	GetPassengerFeedbackByBookingCode(context.Context, *GetPassengerFeedbackRequest) (*GetPassengerFeedbackCodeResponse, error)
	DeletePassengerFeedbackPassengerId(context.Context, *DeletePassengerFeedbackRequest) (*DeletePassengerFeedbackResponse, error)
}

// UnimplementedPassengerFeedbackServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPassengerFeedbackServiceServer struct {
}

func (*UnimplementedPassengerFeedbackServiceServer) AddPassengerFeedback(ctx context.Context, req *PassengerFeedback) (*AddPassengerFeedbackResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPassengerFeedback not implemented")
}
func (*UnimplementedPassengerFeedbackServiceServer) GetPassengerFeedbackByPassengerId(ctx context.Context, req *GetPassengerFeedbackRequest) (*GetPassengerFeedbackIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassengerFeedbackByPassengerId not implemented")
}
func (*UnimplementedPassengerFeedbackServiceServer) GetPassengerFeedbackByBookingCode(ctx context.Context, req *GetPassengerFeedbackRequest) (*GetPassengerFeedbackCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassengerFeedbackByBookingCode not implemented")
}
func (*UnimplementedPassengerFeedbackServiceServer) DeletePassengerFeedbackPassengerId(ctx context.Context, req *DeletePassengerFeedbackRequest) (*DeletePassengerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassengerFeedbackPassengerId not implemented")
}

func RegisterPassengerFeedbackServiceServer(s *grpc.Server, srv PassengerFeedbackServiceServer) {
	s.RegisterService(&_PassengerFeedbackService_serviceDesc, srv)
}

func _PassengerFeedbackService_AddPassengerFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerFeedback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).AddPassengerFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.PassengerFeedbackService/AddPassengerFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).AddPassengerFeedback(ctx, req.(*PassengerFeedback))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetPassengerFeedbackByPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetPassengerFeedbackByPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.PassengerFeedbackService/GetPassengerFeedbackByPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetPassengerFeedbackByPassengerId(ctx, req.(*GetPassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_GetPassengerFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).GetPassengerFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.PassengerFeedbackService/GetPassengerFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).GetPassengerFeedbackByBookingCode(ctx, req.(*GetPassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedbackService_DeletePassengerFeedbackPassengerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePassengerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServiceServer).DeletePassengerFeedbackPassengerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/passengerfeedback.PassengerFeedbackService/DeletePassengerFeedbackPassengerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServiceServer).DeletePassengerFeedbackPassengerId(ctx, req.(*DeletePassengerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassengerFeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "passengerfeedback.PassengerFeedbackService",
	HandlerType: (*PassengerFeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPassengerFeedback",
			Handler:    _PassengerFeedbackService_AddPassengerFeedback_Handler,
		},
		{
			MethodName: "GetPassengerFeedbackByPassengerId",
			Handler:    _PassengerFeedbackService_GetPassengerFeedbackByPassengerId_Handler,
		},
		{
			MethodName: "GetPassengerFeedbackByBookingCode",
			Handler:    _PassengerFeedbackService_GetPassengerFeedbackByBookingCode_Handler,
		},
		{
			MethodName: "DeletePassengerFeedbackPassengerId",
			Handler:    _PassengerFeedbackService_DeletePassengerFeedbackPassengerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passengerfeedback.proto",
}
